// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocation.proto

package biz.ganttproject.core.proto;

public final class AllocationProto {
  private AllocationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AllocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 resource_id = 1;
    boolean hasResourceId();
    int getResourceId();
    
    // required int32 task_id = 2;
    boolean hasTaskId();
    int getTaskId();
    
    // optional float load = 3 [default = 100];
    boolean hasLoad();
    float getLoad();
    
    // optional string role_id = 4;
    boolean hasRoleId();
    String getRoleId();
    
    // optional bool is_coordinator = 5;
    boolean hasIsCoordinator();
    boolean getIsCoordinator();
  }
  public static final class Allocation extends
      com.google.protobuf.GeneratedMessage
      implements AllocationOrBuilder {
    // Use Allocation.newBuilder() to construct.
    private Allocation(Builder builder) {
      super(builder);
    }
    private Allocation(boolean noInit) {}
    
    private static final Allocation defaultInstance;
    public static Allocation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Allocation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_Allocation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_Allocation_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 resource_id = 1;
    public static final int RESOURCE_ID_FIELD_NUMBER = 1;
    private int resourceId_;
    public boolean hasResourceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResourceId() {
      return resourceId_;
    }
    
    // required int32 task_id = 2;
    public static final int TASK_ID_FIELD_NUMBER = 2;
    private int taskId_;
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTaskId() {
      return taskId_;
    }
    
    // optional float load = 3 [default = 100];
    public static final int LOAD_FIELD_NUMBER = 3;
    private float load_;
    public boolean hasLoad() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getLoad() {
      return load_;
    }
    
    // optional string role_id = 4;
    public static final int ROLE_ID_FIELD_NUMBER = 4;
    private java.lang.Object roleId_;
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getRoleId() {
      java.lang.Object ref = roleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          roleId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoleIdBytes() {
      java.lang.Object ref = roleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        roleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool is_coordinator = 5;
    public static final int IS_COORDINATOR_FIELD_NUMBER = 5;
    private boolean isCoordinator_;
    public boolean hasIsCoordinator() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getIsCoordinator() {
      return isCoordinator_;
    }
    
    private void initFields() {
      resourceId_ = 0;
      taskId_ = 0;
      load_ = 100F;
      roleId_ = "";
      isCoordinator_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResourceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, load_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRoleIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isCoordinator_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, load_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRoleIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isCoordinator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.Allocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.AllocationProto.Allocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_Allocation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_Allocation_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.AllocationProto.Allocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        load_ = 100F;
        bitField0_ = (bitField0_ & ~0x00000004);
        roleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        isCoordinator_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.AllocationProto.Allocation.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.AllocationProto.Allocation getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.AllocationProto.Allocation.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.AllocationProto.Allocation build() {
        biz.ganttproject.core.proto.AllocationProto.Allocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.AllocationProto.Allocation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.AllocationProto.Allocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.AllocationProto.Allocation buildPartial() {
        biz.ganttproject.core.proto.AllocationProto.Allocation result = new biz.ganttproject.core.proto.AllocationProto.Allocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resourceId_ = resourceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.load_ = load_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isCoordinator_ = isCoordinator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.AllocationProto.Allocation) {
          return mergeFrom((biz.ganttproject.core.proto.AllocationProto.Allocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.AllocationProto.Allocation other) {
        if (other == biz.ganttproject.core.proto.AllocationProto.Allocation.getDefaultInstance()) return this;
        if (other.hasResourceId()) {
          setResourceId(other.getResourceId());
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasLoad()) {
          setLoad(other.getLoad());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasIsCoordinator()) {
          setIsCoordinator(other.getIsCoordinator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResourceId()) {
          
          return false;
        }
        if (!hasTaskId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resourceId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              taskId_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              load_ = input.readFloat();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              roleId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isCoordinator_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 resource_id = 1;
      private int resourceId_ ;
      public boolean hasResourceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResourceId() {
        return resourceId_;
      }
      public Builder setResourceId(int value) {
        bitField0_ |= 0x00000001;
        resourceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearResourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resourceId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 task_id = 2;
      private int taskId_ ;
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTaskId() {
        return taskId_;
      }
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = 0;
        onChanged();
        return this;
      }
      
      // optional float load = 3 [default = 100];
      private float load_ = 100F;
      public boolean hasLoad() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getLoad() {
        return load_;
      }
      public Builder setLoad(float value) {
        bitField0_ |= 0x00000004;
        load_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoad() {
        bitField0_ = (bitField0_ & ~0x00000004);
        load_ = 100F;
        onChanged();
        return this;
      }
      
      // optional string role_id = 4;
      private java.lang.Object roleId_ = "";
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getRoleId() {
        java.lang.Object ref = roleId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          roleId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoleId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        roleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roleId_ = getDefaultInstance().getRoleId();
        onChanged();
        return this;
      }
      void setRoleId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        roleId_ = value;
        onChanged();
      }
      
      // optional bool is_coordinator = 5;
      private boolean isCoordinator_ ;
      public boolean hasIsCoordinator() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getIsCoordinator() {
        return isCoordinator_;
      }
      public Builder setIsCoordinator(boolean value) {
        bitField0_ |= 0x00000010;
        isCoordinator_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsCoordinator() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isCoordinator_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.Allocation)
    }
    
    static {
      defaultInstance = new Allocation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.Allocation)
  }
  
  public interface AllocationListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ganttproject.Allocation allocation = 1;
    java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation> 
        getAllocationList();
    biz.ganttproject.core.proto.AllocationProto.Allocation getAllocation(int index);
    int getAllocationCount();
    java.util.List<? extends biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder> 
        getAllocationOrBuilderList();
    biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder getAllocationOrBuilder(
        int index);
  }
  public static final class AllocationList extends
      com.google.protobuf.GeneratedMessage
      implements AllocationListOrBuilder {
    // Use AllocationList.newBuilder() to construct.
    private AllocationList(Builder builder) {
      super(builder);
    }
    private AllocationList(boolean noInit) {}
    
    private static final AllocationList defaultInstance;
    public static AllocationList getDefaultInstance() {
      return defaultInstance;
    }
    
    public AllocationList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_AllocationList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_AllocationList_fieldAccessorTable;
    }
    
    // repeated .ganttproject.Allocation allocation = 1;
    public static final int ALLOCATION_FIELD_NUMBER = 1;
    private java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation> allocation_;
    public java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation> getAllocationList() {
      return allocation_;
    }
    public java.util.List<? extends biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder> 
        getAllocationOrBuilderList() {
      return allocation_;
    }
    public int getAllocationCount() {
      return allocation_.size();
    }
    public biz.ganttproject.core.proto.AllocationProto.Allocation getAllocation(int index) {
      return allocation_.get(index);
    }
    public biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder getAllocationOrBuilder(
        int index) {
      return allocation_.get(index);
    }
    
    private void initFields() {
      allocation_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAllocationCount(); i++) {
        if (!getAllocation(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < allocation_.size(); i++) {
        output.writeMessage(1, allocation_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < allocation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allocation_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.AllocationProto.AllocationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.AllocationProto.AllocationList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.AllocationProto.AllocationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_AllocationList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.AllocationProto.internal_static_ganttproject_AllocationList_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.AllocationProto.AllocationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAllocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (allocationBuilder_ == null) {
          allocation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allocationBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.AllocationProto.AllocationList.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.AllocationProto.AllocationList getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.AllocationProto.AllocationList.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.AllocationProto.AllocationList build() {
        biz.ganttproject.core.proto.AllocationProto.AllocationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.AllocationProto.AllocationList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.AllocationProto.AllocationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.AllocationProto.AllocationList buildPartial() {
        biz.ganttproject.core.proto.AllocationProto.AllocationList result = new biz.ganttproject.core.proto.AllocationProto.AllocationList(this);
        int from_bitField0_ = bitField0_;
        if (allocationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allocation_ = java.util.Collections.unmodifiableList(allocation_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allocation_ = allocation_;
        } else {
          result.allocation_ = allocationBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.AllocationProto.AllocationList) {
          return mergeFrom((biz.ganttproject.core.proto.AllocationProto.AllocationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.AllocationProto.AllocationList other) {
        if (other == biz.ganttproject.core.proto.AllocationProto.AllocationList.getDefaultInstance()) return this;
        if (allocationBuilder_ == null) {
          if (!other.allocation_.isEmpty()) {
            if (allocation_.isEmpty()) {
              allocation_ = other.allocation_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllocationIsMutable();
              allocation_.addAll(other.allocation_);
            }
            onChanged();
          }
        } else {
          if (!other.allocation_.isEmpty()) {
            if (allocationBuilder_.isEmpty()) {
              allocationBuilder_.dispose();
              allocationBuilder_ = null;
              allocation_ = other.allocation_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allocationBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAllocationFieldBuilder() : null;
            } else {
              allocationBuilder_.addAllMessages(other.allocation_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAllocationCount(); i++) {
          if (!getAllocation(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              biz.ganttproject.core.proto.AllocationProto.Allocation.Builder subBuilder = biz.ganttproject.core.proto.AllocationProto.Allocation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAllocation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ganttproject.Allocation allocation = 1;
      private java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation> allocation_ =
        java.util.Collections.emptyList();
      private void ensureAllocationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allocation_ = new java.util.ArrayList<biz.ganttproject.core.proto.AllocationProto.Allocation>(allocation_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.AllocationProto.Allocation, biz.ganttproject.core.proto.AllocationProto.Allocation.Builder, biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder> allocationBuilder_;
      
      public java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation> getAllocationList() {
        if (allocationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allocation_);
        } else {
          return allocationBuilder_.getMessageList();
        }
      }
      public int getAllocationCount() {
        if (allocationBuilder_ == null) {
          return allocation_.size();
        } else {
          return allocationBuilder_.getCount();
        }
      }
      public biz.ganttproject.core.proto.AllocationProto.Allocation getAllocation(int index) {
        if (allocationBuilder_ == null) {
          return allocation_.get(index);
        } else {
          return allocationBuilder_.getMessage(index);
        }
      }
      public Builder setAllocation(
          int index, biz.ganttproject.core.proto.AllocationProto.Allocation value) {
        if (allocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllocationIsMutable();
          allocation_.set(index, value);
          onChanged();
        } else {
          allocationBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAllocation(
          int index, biz.ganttproject.core.proto.AllocationProto.Allocation.Builder builderForValue) {
        if (allocationBuilder_ == null) {
          ensureAllocationIsMutable();
          allocation_.set(index, builderForValue.build());
          onChanged();
        } else {
          allocationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllocation(biz.ganttproject.core.proto.AllocationProto.Allocation value) {
        if (allocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllocationIsMutable();
          allocation_.add(value);
          onChanged();
        } else {
          allocationBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAllocation(
          int index, biz.ganttproject.core.proto.AllocationProto.Allocation value) {
        if (allocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllocationIsMutable();
          allocation_.add(index, value);
          onChanged();
        } else {
          allocationBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAllocation(
          biz.ganttproject.core.proto.AllocationProto.Allocation.Builder builderForValue) {
        if (allocationBuilder_ == null) {
          ensureAllocationIsMutable();
          allocation_.add(builderForValue.build());
          onChanged();
        } else {
          allocationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAllocation(
          int index, biz.ganttproject.core.proto.AllocationProto.Allocation.Builder builderForValue) {
        if (allocationBuilder_ == null) {
          ensureAllocationIsMutable();
          allocation_.add(index, builderForValue.build());
          onChanged();
        } else {
          allocationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAllocation(
          java.lang.Iterable<? extends biz.ganttproject.core.proto.AllocationProto.Allocation> values) {
        if (allocationBuilder_ == null) {
          ensureAllocationIsMutable();
          super.addAll(values, allocation_);
          onChanged();
        } else {
          allocationBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAllocation() {
        if (allocationBuilder_ == null) {
          allocation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allocationBuilder_.clear();
        }
        return this;
      }
      public Builder removeAllocation(int index) {
        if (allocationBuilder_ == null) {
          ensureAllocationIsMutable();
          allocation_.remove(index);
          onChanged();
        } else {
          allocationBuilder_.remove(index);
        }
        return this;
      }
      public biz.ganttproject.core.proto.AllocationProto.Allocation.Builder getAllocationBuilder(
          int index) {
        return getAllocationFieldBuilder().getBuilder(index);
      }
      public biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder getAllocationOrBuilder(
          int index) {
        if (allocationBuilder_ == null) {
          return allocation_.get(index);  } else {
          return allocationBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder> 
           getAllocationOrBuilderList() {
        if (allocationBuilder_ != null) {
          return allocationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allocation_);
        }
      }
      public biz.ganttproject.core.proto.AllocationProto.Allocation.Builder addAllocationBuilder() {
        return getAllocationFieldBuilder().addBuilder(
            biz.ganttproject.core.proto.AllocationProto.Allocation.getDefaultInstance());
      }
      public biz.ganttproject.core.proto.AllocationProto.Allocation.Builder addAllocationBuilder(
          int index) {
        return getAllocationFieldBuilder().addBuilder(
            index, biz.ganttproject.core.proto.AllocationProto.Allocation.getDefaultInstance());
      }
      public java.util.List<biz.ganttproject.core.proto.AllocationProto.Allocation.Builder> 
           getAllocationBuilderList() {
        return getAllocationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.AllocationProto.Allocation, biz.ganttproject.core.proto.AllocationProto.Allocation.Builder, biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder> 
          getAllocationFieldBuilder() {
        if (allocationBuilder_ == null) {
          allocationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              biz.ganttproject.core.proto.AllocationProto.Allocation, biz.ganttproject.core.proto.AllocationProto.Allocation.Builder, biz.ganttproject.core.proto.AllocationProto.AllocationOrBuilder>(
                  allocation_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allocation_ = null;
        }
        return allocationBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.AllocationList)
    }
    
    static {
      defaultInstance = new AllocationList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.AllocationList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_Allocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_Allocation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_AllocationList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_AllocationList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020allocation.proto\022\014ganttproject\"n\n\nAllo" +
      "cation\022\023\n\013resource_id\030\001 \002(\005\022\017\n\007task_id\030\002" +
      " \002(\005\022\021\n\004load\030\003 \001(\002:\003100\022\017\n\007role_id\030\004 \001(\t" +
      "\022\026\n\016is_coordinator\030\005 \001(\010\">\n\016AllocationLi" +
      "st\022,\n\nallocation\030\001 \003(\0132\030.ganttproject.Al" +
      "locationB.\n\033biz.ganttproject.core.protoB" +
      "\017AllocationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_Allocation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_Allocation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_Allocation_descriptor,
              new java.lang.String[] { "ResourceId", "TaskId", "Load", "RoleId", "IsCoordinator", },
              biz.ganttproject.core.proto.AllocationProto.Allocation.class,
              biz.ganttproject.core.proto.AllocationProto.Allocation.Builder.class);
          internal_static_ganttproject_AllocationList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ganttproject_AllocationList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_AllocationList_descriptor,
              new java.lang.String[] { "Allocation", },
              biz.ganttproject.core.proto.AllocationProto.AllocationList.class,
              biz.ganttproject.core.proto.AllocationProto.AllocationList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
