// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package biz.ganttproject.core.proto;

public final class FileProto {
  private FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ganttproject.Project project = 1;
    boolean hasProject();
    biz.ganttproject.core.proto.ProjectProto.Project getProject();
    biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder getProjectOrBuilder();
    
    // repeated .ganttproject.GanttView gantt_view = 2;
    java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView> 
        getGanttViewList();
    biz.ganttproject.core.proto.ViewProto.GanttView getGanttView(int index);
    int getGanttViewCount();
    java.util.List<? extends biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder> 
        getGanttViewOrBuilderList();
    biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder getGanttViewOrBuilder(
        int index);
  }
  public static final class File extends
      com.google.protobuf.GeneratedMessage
      implements FileOrBuilder {
    // Use File.newBuilder() to construct.
    private File(Builder builder) {
      super(builder);
    }
    private File(boolean noInit) {}
    
    private static final File defaultInstance;
    public static File getDefaultInstance() {
      return defaultInstance;
    }
    
    public File getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.FileProto.internal_static_ganttproject_File_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.FileProto.internal_static_ganttproject_File_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ganttproject.Project project = 1;
    public static final int PROJECT_FIELD_NUMBER = 1;
    private biz.ganttproject.core.proto.ProjectProto.Project project_;
    public boolean hasProject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public biz.ganttproject.core.proto.ProjectProto.Project getProject() {
      return project_;
    }
    public biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder getProjectOrBuilder() {
      return project_;
    }
    
    // repeated .ganttproject.GanttView gantt_view = 2;
    public static final int GANTT_VIEW_FIELD_NUMBER = 2;
    private java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView> ganttView_;
    public java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView> getGanttViewList() {
      return ganttView_;
    }
    public java.util.List<? extends biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder> 
        getGanttViewOrBuilderList() {
      return ganttView_;
    }
    public int getGanttViewCount() {
      return ganttView_.size();
    }
    public biz.ganttproject.core.proto.ViewProto.GanttView getGanttView(int index) {
      return ganttView_.get(index);
    }
    public biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder getGanttViewOrBuilder(
        int index) {
      return ganttView_.get(index);
    }
    
    private void initFields() {
      project_ = biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance();
      ganttView_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getProject().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGanttViewCount(); i++) {
        if (!getGanttView(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, project_);
      }
      for (int i = 0; i < ganttView_.size(); i++) {
        output.writeMessage(2, ganttView_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, project_);
      }
      for (int i = 0; i < ganttView_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ganttView_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.FileProto.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.FileProto.File prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.FileProto.FileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.FileProto.internal_static_ganttproject_File_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.FileProto.internal_static_ganttproject_File_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.FileProto.File.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProjectFieldBuilder();
          getGanttViewFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (projectBuilder_ == null) {
          project_ = biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance();
        } else {
          projectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (ganttViewBuilder_ == null) {
          ganttView_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ganttViewBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.FileProto.File.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.FileProto.File getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.FileProto.File.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.FileProto.File build() {
        biz.ganttproject.core.proto.FileProto.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.FileProto.File buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.FileProto.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.FileProto.File buildPartial() {
        biz.ganttproject.core.proto.FileProto.File result = new biz.ganttproject.core.proto.FileProto.File(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (projectBuilder_ == null) {
          result.project_ = project_;
        } else {
          result.project_ = projectBuilder_.build();
        }
        if (ganttViewBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ganttView_ = java.util.Collections.unmodifiableList(ganttView_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ganttView_ = ganttView_;
        } else {
          result.ganttView_ = ganttViewBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.FileProto.File) {
          return mergeFrom((biz.ganttproject.core.proto.FileProto.File)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.FileProto.File other) {
        if (other == biz.ganttproject.core.proto.FileProto.File.getDefaultInstance()) return this;
        if (other.hasProject()) {
          mergeProject(other.getProject());
        }
        if (ganttViewBuilder_ == null) {
          if (!other.ganttView_.isEmpty()) {
            if (ganttView_.isEmpty()) {
              ganttView_ = other.ganttView_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGanttViewIsMutable();
              ganttView_.addAll(other.ganttView_);
            }
            onChanged();
          }
        } else {
          if (!other.ganttView_.isEmpty()) {
            if (ganttViewBuilder_.isEmpty()) {
              ganttViewBuilder_.dispose();
              ganttViewBuilder_ = null;
              ganttView_ = other.ganttView_;
              bitField0_ = (bitField0_ & ~0x00000002);
              ganttViewBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGanttViewFieldBuilder() : null;
            } else {
              ganttViewBuilder_.addAllMessages(other.ganttView_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProject()) {
          
          return false;
        }
        if (!getProject().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getGanttViewCount(); i++) {
          if (!getGanttView(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              biz.ganttproject.core.proto.ProjectProto.Project.Builder subBuilder = biz.ganttproject.core.proto.ProjectProto.Project.newBuilder();
              if (hasProject()) {
                subBuilder.mergeFrom(getProject());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProject(subBuilder.buildPartial());
              break;
            }
            case 18: {
              biz.ganttproject.core.proto.ViewProto.GanttView.Builder subBuilder = biz.ganttproject.core.proto.ViewProto.GanttView.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGanttView(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ganttproject.Project project = 1;
      private biz.ganttproject.core.proto.ProjectProto.Project project_ = biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.ProjectProto.Project, biz.ganttproject.core.proto.ProjectProto.Project.Builder, biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder> projectBuilder_;
      public boolean hasProject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public biz.ganttproject.core.proto.ProjectProto.Project getProject() {
        if (projectBuilder_ == null) {
          return project_;
        } else {
          return projectBuilder_.getMessage();
        }
      }
      public Builder setProject(biz.ganttproject.core.proto.ProjectProto.Project value) {
        if (projectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          project_ = value;
          onChanged();
        } else {
          projectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setProject(
          biz.ganttproject.core.proto.ProjectProto.Project.Builder builderForValue) {
        if (projectBuilder_ == null) {
          project_ = builderForValue.build();
          onChanged();
        } else {
          projectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeProject(biz.ganttproject.core.proto.ProjectProto.Project value) {
        if (projectBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              project_ != biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance()) {
            project_ =
              biz.ganttproject.core.proto.ProjectProto.Project.newBuilder(project_).mergeFrom(value).buildPartial();
          } else {
            project_ = value;
          }
          onChanged();
        } else {
          projectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearProject() {
        if (projectBuilder_ == null) {
          project_ = biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance();
          onChanged();
        } else {
          projectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public biz.ganttproject.core.proto.ProjectProto.Project.Builder getProjectBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getProjectFieldBuilder().getBuilder();
      }
      public biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder getProjectOrBuilder() {
        if (projectBuilder_ != null) {
          return projectBuilder_.getMessageOrBuilder();
        } else {
          return project_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.ProjectProto.Project, biz.ganttproject.core.proto.ProjectProto.Project.Builder, biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder> 
          getProjectFieldBuilder() {
        if (projectBuilder_ == null) {
          projectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              biz.ganttproject.core.proto.ProjectProto.Project, biz.ganttproject.core.proto.ProjectProto.Project.Builder, biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder>(
                  project_,
                  getParentForChildren(),
                  isClean());
          project_ = null;
        }
        return projectBuilder_;
      }
      
      // repeated .ganttproject.GanttView gantt_view = 2;
      private java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView> ganttView_ =
        java.util.Collections.emptyList();
      private void ensureGanttViewIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ganttView_ = new java.util.ArrayList<biz.ganttproject.core.proto.ViewProto.GanttView>(ganttView_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.ViewProto.GanttView, biz.ganttproject.core.proto.ViewProto.GanttView.Builder, biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder> ganttViewBuilder_;
      
      public java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView> getGanttViewList() {
        if (ganttViewBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ganttView_);
        } else {
          return ganttViewBuilder_.getMessageList();
        }
      }
      public int getGanttViewCount() {
        if (ganttViewBuilder_ == null) {
          return ganttView_.size();
        } else {
          return ganttViewBuilder_.getCount();
        }
      }
      public biz.ganttproject.core.proto.ViewProto.GanttView getGanttView(int index) {
        if (ganttViewBuilder_ == null) {
          return ganttView_.get(index);
        } else {
          return ganttViewBuilder_.getMessage(index);
        }
      }
      public Builder setGanttView(
          int index, biz.ganttproject.core.proto.ViewProto.GanttView value) {
        if (ganttViewBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGanttViewIsMutable();
          ganttView_.set(index, value);
          onChanged();
        } else {
          ganttViewBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGanttView(
          int index, biz.ganttproject.core.proto.ViewProto.GanttView.Builder builderForValue) {
        if (ganttViewBuilder_ == null) {
          ensureGanttViewIsMutable();
          ganttView_.set(index, builderForValue.build());
          onChanged();
        } else {
          ganttViewBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGanttView(biz.ganttproject.core.proto.ViewProto.GanttView value) {
        if (ganttViewBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGanttViewIsMutable();
          ganttView_.add(value);
          onChanged();
        } else {
          ganttViewBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGanttView(
          int index, biz.ganttproject.core.proto.ViewProto.GanttView value) {
        if (ganttViewBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGanttViewIsMutable();
          ganttView_.add(index, value);
          onChanged();
        } else {
          ganttViewBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGanttView(
          biz.ganttproject.core.proto.ViewProto.GanttView.Builder builderForValue) {
        if (ganttViewBuilder_ == null) {
          ensureGanttViewIsMutable();
          ganttView_.add(builderForValue.build());
          onChanged();
        } else {
          ganttViewBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGanttView(
          int index, biz.ganttproject.core.proto.ViewProto.GanttView.Builder builderForValue) {
        if (ganttViewBuilder_ == null) {
          ensureGanttViewIsMutable();
          ganttView_.add(index, builderForValue.build());
          onChanged();
        } else {
          ganttViewBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGanttView(
          java.lang.Iterable<? extends biz.ganttproject.core.proto.ViewProto.GanttView> values) {
        if (ganttViewBuilder_ == null) {
          ensureGanttViewIsMutable();
          super.addAll(values, ganttView_);
          onChanged();
        } else {
          ganttViewBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGanttView() {
        if (ganttViewBuilder_ == null) {
          ganttView_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          ganttViewBuilder_.clear();
        }
        return this;
      }
      public Builder removeGanttView(int index) {
        if (ganttViewBuilder_ == null) {
          ensureGanttViewIsMutable();
          ganttView_.remove(index);
          onChanged();
        } else {
          ganttViewBuilder_.remove(index);
        }
        return this;
      }
      public biz.ganttproject.core.proto.ViewProto.GanttView.Builder getGanttViewBuilder(
          int index) {
        return getGanttViewFieldBuilder().getBuilder(index);
      }
      public biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder getGanttViewOrBuilder(
          int index) {
        if (ganttViewBuilder_ == null) {
          return ganttView_.get(index);  } else {
          return ganttViewBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder> 
           getGanttViewOrBuilderList() {
        if (ganttViewBuilder_ != null) {
          return ganttViewBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ganttView_);
        }
      }
      public biz.ganttproject.core.proto.ViewProto.GanttView.Builder addGanttViewBuilder() {
        return getGanttViewFieldBuilder().addBuilder(
            biz.ganttproject.core.proto.ViewProto.GanttView.getDefaultInstance());
      }
      public biz.ganttproject.core.proto.ViewProto.GanttView.Builder addGanttViewBuilder(
          int index) {
        return getGanttViewFieldBuilder().addBuilder(
            index, biz.ganttproject.core.proto.ViewProto.GanttView.getDefaultInstance());
      }
      public java.util.List<biz.ganttproject.core.proto.ViewProto.GanttView.Builder> 
           getGanttViewBuilderList() {
        return getGanttViewFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.ViewProto.GanttView, biz.ganttproject.core.proto.ViewProto.GanttView.Builder, biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder> 
          getGanttViewFieldBuilder() {
        if (ganttViewBuilder_ == null) {
          ganttViewBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              biz.ganttproject.core.proto.ViewProto.GanttView, biz.ganttproject.core.proto.ViewProto.GanttView.Builder, biz.ganttproject.core.proto.ViewProto.GanttViewOrBuilder>(
                  ganttView_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ganttView_ = null;
        }
        return ganttViewBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.File)
    }
    
    static {
      defaultInstance = new File(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.File)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_File_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\022\014ganttproject\032\rproject.prot" +
      "o\032\nview.proto\"[\n\004File\022&\n\007project\030\001 \002(\0132\025" +
      ".ganttproject.Project\022+\n\ngantt_view\030\002 \003(" +
      "\0132\027.ganttproject.GanttViewB(\n\033biz.ganttp" +
      "roject.core.protoB\tFileProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_File_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_File_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_File_descriptor,
              new java.lang.String[] { "Project", "GanttView", },
              biz.ganttproject.core.proto.FileProto.File.class,
              biz.ganttproject.core.proto.FileProto.File.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          biz.ganttproject.core.proto.ProjectProto.getDescriptor(),
          biz.ganttproject.core.proto.ViewProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
