// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: industry.proto

package biz.ganttproject.core.proto;

public final class IndustryProto {
  private IndustryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JobOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
  }
  public static final class Job extends
      com.google.protobuf.GeneratedMessage
      implements JobOrBuilder {
    // Use Job.newBuilder() to construct.
    private Job(Builder builder) {
      super(builder);
    }
    private Job(boolean noInit) {}
    
    private static final Job defaultInstance;
    public static Job getDefaultInstance() {
      return defaultInstance;
    }
    
    public Job getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Job_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Job_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Job parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.IndustryProto.Job prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.IndustryProto.JobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Job_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Job_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.IndustryProto.Job.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.IndustryProto.Job.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Job getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.IndustryProto.Job.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Job build() {
        biz.ganttproject.core.proto.IndustryProto.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.IndustryProto.Job buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.IndustryProto.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Job buildPartial() {
        biz.ganttproject.core.proto.IndustryProto.Job result = new biz.ganttproject.core.proto.IndustryProto.Job(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.IndustryProto.Job) {
          return mergeFrom((biz.ganttproject.core.proto.IndustryProto.Job)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.IndustryProto.Job other) {
        if (other == biz.ganttproject.core.proto.IndustryProto.Job.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.Job)
    }
    
    static {
      defaultInstance = new Job(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.Job)
  }
  
  public interface IndustryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // repeated .ganttproject.Job job = 2;
    java.util.List<biz.ganttproject.core.proto.IndustryProto.Job> 
        getJobList();
    biz.ganttproject.core.proto.IndustryProto.Job getJob(int index);
    int getJobCount();
    java.util.List<? extends biz.ganttproject.core.proto.IndustryProto.JobOrBuilder> 
        getJobOrBuilderList();
    biz.ganttproject.core.proto.IndustryProto.JobOrBuilder getJobOrBuilder(
        int index);
  }
  public static final class Industry extends
      com.google.protobuf.GeneratedMessage
      implements IndustryOrBuilder {
    // Use Industry.newBuilder() to construct.
    private Industry(Builder builder) {
      super(builder);
    }
    private Industry(boolean noInit) {}
    
    private static final Industry defaultInstance;
    public static Industry getDefaultInstance() {
      return defaultInstance;
    }
    
    public Industry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Industry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Industry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .ganttproject.Job job = 2;
    public static final int JOB_FIELD_NUMBER = 2;
    private java.util.List<biz.ganttproject.core.proto.IndustryProto.Job> job_;
    public java.util.List<biz.ganttproject.core.proto.IndustryProto.Job> getJobList() {
      return job_;
    }
    public java.util.List<? extends biz.ganttproject.core.proto.IndustryProto.JobOrBuilder> 
        getJobOrBuilderList() {
      return job_;
    }
    public int getJobCount() {
      return job_.size();
    }
    public biz.ganttproject.core.proto.IndustryProto.Job getJob(int index) {
      return job_.get(index);
    }
    public biz.ganttproject.core.proto.IndustryProto.JobOrBuilder getJobOrBuilder(
        int index) {
      return job_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      job_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getJobCount(); i++) {
        if (!getJob(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      for (int i = 0; i < job_.size(); i++) {
        output.writeMessage(2, job_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      for (int i = 0; i < job_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, job_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.IndustryProto.Industry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.IndustryProto.Industry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.IndustryProto.IndustryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Industry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.IndustryProto.internal_static_ganttproject_Industry_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.IndustryProto.Industry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJobFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (jobBuilder_ == null) {
          job_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          jobBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.IndustryProto.Industry.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Industry getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.IndustryProto.Industry.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Industry build() {
        biz.ganttproject.core.proto.IndustryProto.Industry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.IndustryProto.Industry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.IndustryProto.Industry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.IndustryProto.Industry buildPartial() {
        biz.ganttproject.core.proto.IndustryProto.Industry result = new biz.ganttproject.core.proto.IndustryProto.Industry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (jobBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            job_ = java.util.Collections.unmodifiableList(job_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.job_ = job_;
        } else {
          result.job_ = jobBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.IndustryProto.Industry) {
          return mergeFrom((biz.ganttproject.core.proto.IndustryProto.Industry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.IndustryProto.Industry other) {
        if (other == biz.ganttproject.core.proto.IndustryProto.Industry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (jobBuilder_ == null) {
          if (!other.job_.isEmpty()) {
            if (job_.isEmpty()) {
              job_ = other.job_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureJobIsMutable();
              job_.addAll(other.job_);
            }
            onChanged();
          }
        } else {
          if (!other.job_.isEmpty()) {
            if (jobBuilder_.isEmpty()) {
              jobBuilder_.dispose();
              jobBuilder_ = null;
              job_ = other.job_;
              bitField0_ = (bitField0_ & ~0x00000002);
              jobBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJobFieldBuilder() : null;
            } else {
              jobBuilder_.addAllMessages(other.job_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getJobCount(); i++) {
          if (!getJob(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              biz.ganttproject.core.proto.IndustryProto.Job.Builder subBuilder = biz.ganttproject.core.proto.IndustryProto.Job.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addJob(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // repeated .ganttproject.Job job = 2;
      private java.util.List<biz.ganttproject.core.proto.IndustryProto.Job> job_ =
        java.util.Collections.emptyList();
      private void ensureJobIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          job_ = new java.util.ArrayList<biz.ganttproject.core.proto.IndustryProto.Job>(job_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.IndustryProto.Job, biz.ganttproject.core.proto.IndustryProto.Job.Builder, biz.ganttproject.core.proto.IndustryProto.JobOrBuilder> jobBuilder_;
      
      public java.util.List<biz.ganttproject.core.proto.IndustryProto.Job> getJobList() {
        if (jobBuilder_ == null) {
          return java.util.Collections.unmodifiableList(job_);
        } else {
          return jobBuilder_.getMessageList();
        }
      }
      public int getJobCount() {
        if (jobBuilder_ == null) {
          return job_.size();
        } else {
          return jobBuilder_.getCount();
        }
      }
      public biz.ganttproject.core.proto.IndustryProto.Job getJob(int index) {
        if (jobBuilder_ == null) {
          return job_.get(index);
        } else {
          return jobBuilder_.getMessage(index);
        }
      }
      public Builder setJob(
          int index, biz.ganttproject.core.proto.IndustryProto.Job value) {
        if (jobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobIsMutable();
          job_.set(index, value);
          onChanged();
        } else {
          jobBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setJob(
          int index, biz.ganttproject.core.proto.IndustryProto.Job.Builder builderForValue) {
        if (jobBuilder_ == null) {
          ensureJobIsMutable();
          job_.set(index, builderForValue.build());
          onChanged();
        } else {
          jobBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addJob(biz.ganttproject.core.proto.IndustryProto.Job value) {
        if (jobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobIsMutable();
          job_.add(value);
          onChanged();
        } else {
          jobBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addJob(
          int index, biz.ganttproject.core.proto.IndustryProto.Job value) {
        if (jobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobIsMutable();
          job_.add(index, value);
          onChanged();
        } else {
          jobBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addJob(
          biz.ganttproject.core.proto.IndustryProto.Job.Builder builderForValue) {
        if (jobBuilder_ == null) {
          ensureJobIsMutable();
          job_.add(builderForValue.build());
          onChanged();
        } else {
          jobBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addJob(
          int index, biz.ganttproject.core.proto.IndustryProto.Job.Builder builderForValue) {
        if (jobBuilder_ == null) {
          ensureJobIsMutable();
          job_.add(index, builderForValue.build());
          onChanged();
        } else {
          jobBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllJob(
          java.lang.Iterable<? extends biz.ganttproject.core.proto.IndustryProto.Job> values) {
        if (jobBuilder_ == null) {
          ensureJobIsMutable();
          super.addAll(values, job_);
          onChanged();
        } else {
          jobBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearJob() {
        if (jobBuilder_ == null) {
          job_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          jobBuilder_.clear();
        }
        return this;
      }
      public Builder removeJob(int index) {
        if (jobBuilder_ == null) {
          ensureJobIsMutable();
          job_.remove(index);
          onChanged();
        } else {
          jobBuilder_.remove(index);
        }
        return this;
      }
      public biz.ganttproject.core.proto.IndustryProto.Job.Builder getJobBuilder(
          int index) {
        return getJobFieldBuilder().getBuilder(index);
      }
      public biz.ganttproject.core.proto.IndustryProto.JobOrBuilder getJobOrBuilder(
          int index) {
        if (jobBuilder_ == null) {
          return job_.get(index);  } else {
          return jobBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends biz.ganttproject.core.proto.IndustryProto.JobOrBuilder> 
           getJobOrBuilderList() {
        if (jobBuilder_ != null) {
          return jobBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(job_);
        }
      }
      public biz.ganttproject.core.proto.IndustryProto.Job.Builder addJobBuilder() {
        return getJobFieldBuilder().addBuilder(
            biz.ganttproject.core.proto.IndustryProto.Job.getDefaultInstance());
      }
      public biz.ganttproject.core.proto.IndustryProto.Job.Builder addJobBuilder(
          int index) {
        return getJobFieldBuilder().addBuilder(
            index, biz.ganttproject.core.proto.IndustryProto.Job.getDefaultInstance());
      }
      public java.util.List<biz.ganttproject.core.proto.IndustryProto.Job.Builder> 
           getJobBuilderList() {
        return getJobFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.IndustryProto.Job, biz.ganttproject.core.proto.IndustryProto.Job.Builder, biz.ganttproject.core.proto.IndustryProto.JobOrBuilder> 
          getJobFieldBuilder() {
        if (jobBuilder_ == null) {
          jobBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              biz.ganttproject.core.proto.IndustryProto.Job, biz.ganttproject.core.proto.IndustryProto.Job.Builder, biz.ganttproject.core.proto.IndustryProto.JobOrBuilder>(
                  job_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          job_ = null;
        }
        return jobBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.Industry)
    }
    
    static {
      defaultInstance = new Industry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.Industry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_Job_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_Job_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_Industry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_Industry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016industry.proto\022\014ganttproject\"\037\n\003Job\022\n\n" +
      "\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\"6\n\010Industry\022\n\n\002i" +
      "d\030\001 \002(\t\022\036\n\003job\030\002 \003(\0132\021.ganttproject.JobB" +
      ",\n\033biz.ganttproject.core.protoB\rIndustry" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_Job_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_Job_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_Job_descriptor,
              new java.lang.String[] { "Id", "Name", },
              biz.ganttproject.core.proto.IndustryProto.Job.class,
              biz.ganttproject.core.proto.IndustryProto.Job.Builder.class);
          internal_static_ganttproject_Industry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ganttproject_Industry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_Industry_descriptor,
              new java.lang.String[] { "Id", "Job", },
              biz.ganttproject.core.proto.IndustryProto.Industry.class,
              biz.ganttproject.core.proto.IndustryProto.Industry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
