// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project.proto

package biz.ganttproject.core.proto;

public final class ProjectProto {
  private ProjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional string organization = 2;
    boolean hasOrganization();
    String getOrganization();
    
    // optional string project_url = 3;
    boolean hasProjectUrl();
    String getProjectUrl();
    
    // required .ganttproject.TaskList task_list = 4;
    boolean hasTaskList();
    biz.ganttproject.core.proto.TaskProto.TaskList getTaskList();
    biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder getTaskListOrBuilder();
    
    // optional .ganttproject.DependencyList dependency_list = 5;
    boolean hasDependencyList();
    biz.ganttproject.core.proto.TaskProto.DependencyList getDependencyList();
    biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder getDependencyListOrBuilder();
  }
  public static final class Project extends
      com.google.protobuf.GeneratedMessage
      implements ProjectOrBuilder {
    // Use Project.newBuilder() to construct.
    private Project(Builder builder) {
      super(builder);
    }
    private Project(boolean noInit) {}
    
    private static final Project defaultInstance;
    public static Project getDefaultInstance() {
      return defaultInstance;
    }
    
    public Project getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.ProjectProto.internal_static_ganttproject_Project_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.ProjectProto.internal_static_ganttproject_Project_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string organization = 2;
    public static final int ORGANIZATION_FIELD_NUMBER = 2;
    private java.lang.Object organization_;
    public boolean hasOrganization() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getOrganization() {
      java.lang.Object ref = organization_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          organization_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrganizationBytes() {
      java.lang.Object ref = organization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        organization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string project_url = 3;
    public static final int PROJECT_URL_FIELD_NUMBER = 3;
    private java.lang.Object projectUrl_;
    public boolean hasProjectUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getProjectUrl() {
      java.lang.Object ref = projectUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          projectUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProjectUrlBytes() {
      java.lang.Object ref = projectUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        projectUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .ganttproject.TaskList task_list = 4;
    public static final int TASK_LIST_FIELD_NUMBER = 4;
    private biz.ganttproject.core.proto.TaskProto.TaskList taskList_;
    public boolean hasTaskList() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public biz.ganttproject.core.proto.TaskProto.TaskList getTaskList() {
      return taskList_;
    }
    public biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder getTaskListOrBuilder() {
      return taskList_;
    }
    
    // optional .ganttproject.DependencyList dependency_list = 5;
    public static final int DEPENDENCY_LIST_FIELD_NUMBER = 5;
    private biz.ganttproject.core.proto.TaskProto.DependencyList dependencyList_;
    public boolean hasDependencyList() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public biz.ganttproject.core.proto.TaskProto.DependencyList getDependencyList() {
      return dependencyList_;
    }
    public biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder getDependencyListOrBuilder() {
      return dependencyList_;
    }
    
    private void initFields() {
      name_ = "";
      organization_ = "";
      projectUrl_ = "";
      taskList_ = biz.ganttproject.core.proto.TaskProto.TaskList.getDefaultInstance();
      dependencyList_ = biz.ganttproject.core.proto.TaskProto.DependencyList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTaskList()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTaskList().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDependencyList()) {
        if (!getDependencyList().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOrganizationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getProjectUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, taskList_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, dependencyList_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOrganizationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProjectUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, taskList_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, dependencyList_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ProjectProto.Project parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.ProjectProto.Project prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.ProjectProto.ProjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.ProjectProto.internal_static_ganttproject_Project_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.ProjectProto.internal_static_ganttproject_Project_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.ProjectProto.Project.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaskListFieldBuilder();
          getDependencyListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        organization_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        projectUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (taskListBuilder_ == null) {
          taskList_ = biz.ganttproject.core.proto.TaskProto.TaskList.getDefaultInstance();
        } else {
          taskListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (dependencyListBuilder_ == null) {
          dependencyList_ = biz.ganttproject.core.proto.TaskProto.DependencyList.getDefaultInstance();
        } else {
          dependencyListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.ProjectProto.Project.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.ProjectProto.Project getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.ProjectProto.Project build() {
        biz.ganttproject.core.proto.ProjectProto.Project result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.ProjectProto.Project buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.ProjectProto.Project result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.ProjectProto.Project buildPartial() {
        biz.ganttproject.core.proto.ProjectProto.Project result = new biz.ganttproject.core.proto.ProjectProto.Project(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.organization_ = organization_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.projectUrl_ = projectUrl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (taskListBuilder_ == null) {
          result.taskList_ = taskList_;
        } else {
          result.taskList_ = taskListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (dependencyListBuilder_ == null) {
          result.dependencyList_ = dependencyList_;
        } else {
          result.dependencyList_ = dependencyListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.ProjectProto.Project) {
          return mergeFrom((biz.ganttproject.core.proto.ProjectProto.Project)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.ProjectProto.Project other) {
        if (other == biz.ganttproject.core.proto.ProjectProto.Project.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasOrganization()) {
          setOrganization(other.getOrganization());
        }
        if (other.hasProjectUrl()) {
          setProjectUrl(other.getProjectUrl());
        }
        if (other.hasTaskList()) {
          mergeTaskList(other.getTaskList());
        }
        if (other.hasDependencyList()) {
          mergeDependencyList(other.getDependencyList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTaskList()) {
          
          return false;
        }
        if (!getTaskList().isInitialized()) {
          
          return false;
        }
        if (hasDependencyList()) {
          if (!getDependencyList().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              organization_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              projectUrl_ = input.readBytes();
              break;
            }
            case 34: {
              biz.ganttproject.core.proto.TaskProto.TaskList.Builder subBuilder = biz.ganttproject.core.proto.TaskProto.TaskList.newBuilder();
              if (hasTaskList()) {
                subBuilder.mergeFrom(getTaskList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTaskList(subBuilder.buildPartial());
              break;
            }
            case 42: {
              biz.ganttproject.core.proto.TaskProto.DependencyList.Builder subBuilder = biz.ganttproject.core.proto.TaskProto.DependencyList.newBuilder();
              if (hasDependencyList()) {
                subBuilder.mergeFrom(getDependencyList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDependencyList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional string organization = 2;
      private java.lang.Object organization_ = "";
      public boolean hasOrganization() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getOrganization() {
        java.lang.Object ref = organization_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          organization_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrganization(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        organization_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrganization() {
        bitField0_ = (bitField0_ & ~0x00000002);
        organization_ = getDefaultInstance().getOrganization();
        onChanged();
        return this;
      }
      void setOrganization(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        organization_ = value;
        onChanged();
      }
      
      // optional string project_url = 3;
      private java.lang.Object projectUrl_ = "";
      public boolean hasProjectUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getProjectUrl() {
        java.lang.Object ref = projectUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          projectUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProjectUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        projectUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearProjectUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        projectUrl_ = getDefaultInstance().getProjectUrl();
        onChanged();
        return this;
      }
      void setProjectUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        projectUrl_ = value;
        onChanged();
      }
      
      // required .ganttproject.TaskList task_list = 4;
      private biz.ganttproject.core.proto.TaskProto.TaskList taskList_ = biz.ganttproject.core.proto.TaskProto.TaskList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.TaskProto.TaskList, biz.ganttproject.core.proto.TaskProto.TaskList.Builder, biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder> taskListBuilder_;
      public boolean hasTaskList() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public biz.ganttproject.core.proto.TaskProto.TaskList getTaskList() {
        if (taskListBuilder_ == null) {
          return taskList_;
        } else {
          return taskListBuilder_.getMessage();
        }
      }
      public Builder setTaskList(biz.ganttproject.core.proto.TaskProto.TaskList value) {
        if (taskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taskList_ = value;
          onChanged();
        } else {
          taskListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setTaskList(
          biz.ganttproject.core.proto.TaskProto.TaskList.Builder builderForValue) {
        if (taskListBuilder_ == null) {
          taskList_ = builderForValue.build();
          onChanged();
        } else {
          taskListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeTaskList(biz.ganttproject.core.proto.TaskProto.TaskList value) {
        if (taskListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              taskList_ != biz.ganttproject.core.proto.TaskProto.TaskList.getDefaultInstance()) {
            taskList_ =
              biz.ganttproject.core.proto.TaskProto.TaskList.newBuilder(taskList_).mergeFrom(value).buildPartial();
          } else {
            taskList_ = value;
          }
          onChanged();
        } else {
          taskListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearTaskList() {
        if (taskListBuilder_ == null) {
          taskList_ = biz.ganttproject.core.proto.TaskProto.TaskList.getDefaultInstance();
          onChanged();
        } else {
          taskListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public biz.ganttproject.core.proto.TaskProto.TaskList.Builder getTaskListBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTaskListFieldBuilder().getBuilder();
      }
      public biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder getTaskListOrBuilder() {
        if (taskListBuilder_ != null) {
          return taskListBuilder_.getMessageOrBuilder();
        } else {
          return taskList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.TaskProto.TaskList, biz.ganttproject.core.proto.TaskProto.TaskList.Builder, biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder> 
          getTaskListFieldBuilder() {
        if (taskListBuilder_ == null) {
          taskListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              biz.ganttproject.core.proto.TaskProto.TaskList, biz.ganttproject.core.proto.TaskProto.TaskList.Builder, biz.ganttproject.core.proto.TaskProto.TaskListOrBuilder>(
                  taskList_,
                  getParentForChildren(),
                  isClean());
          taskList_ = null;
        }
        return taskListBuilder_;
      }
      
      // optional .ganttproject.DependencyList dependency_list = 5;
      private biz.ganttproject.core.proto.TaskProto.DependencyList dependencyList_ = biz.ganttproject.core.proto.TaskProto.DependencyList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.TaskProto.DependencyList, biz.ganttproject.core.proto.TaskProto.DependencyList.Builder, biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder> dependencyListBuilder_;
      public boolean hasDependencyList() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public biz.ganttproject.core.proto.TaskProto.DependencyList getDependencyList() {
        if (dependencyListBuilder_ == null) {
          return dependencyList_;
        } else {
          return dependencyListBuilder_.getMessage();
        }
      }
      public Builder setDependencyList(biz.ganttproject.core.proto.TaskProto.DependencyList value) {
        if (dependencyListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dependencyList_ = value;
          onChanged();
        } else {
          dependencyListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setDependencyList(
          biz.ganttproject.core.proto.TaskProto.DependencyList.Builder builderForValue) {
        if (dependencyListBuilder_ == null) {
          dependencyList_ = builderForValue.build();
          onChanged();
        } else {
          dependencyListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeDependencyList(biz.ganttproject.core.proto.TaskProto.DependencyList value) {
        if (dependencyListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              dependencyList_ != biz.ganttproject.core.proto.TaskProto.DependencyList.getDefaultInstance()) {
            dependencyList_ =
              biz.ganttproject.core.proto.TaskProto.DependencyList.newBuilder(dependencyList_).mergeFrom(value).buildPartial();
          } else {
            dependencyList_ = value;
          }
          onChanged();
        } else {
          dependencyListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearDependencyList() {
        if (dependencyListBuilder_ == null) {
          dependencyList_ = biz.ganttproject.core.proto.TaskProto.DependencyList.getDefaultInstance();
          onChanged();
        } else {
          dependencyListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public biz.ganttproject.core.proto.TaskProto.DependencyList.Builder getDependencyListBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDependencyListFieldBuilder().getBuilder();
      }
      public biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder getDependencyListOrBuilder() {
        if (dependencyListBuilder_ != null) {
          return dependencyListBuilder_.getMessageOrBuilder();
        } else {
          return dependencyList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          biz.ganttproject.core.proto.TaskProto.DependencyList, biz.ganttproject.core.proto.TaskProto.DependencyList.Builder, biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder> 
          getDependencyListFieldBuilder() {
        if (dependencyListBuilder_ == null) {
          dependencyListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              biz.ganttproject.core.proto.TaskProto.DependencyList, biz.ganttproject.core.proto.TaskProto.DependencyList.Builder, biz.ganttproject.core.proto.TaskProto.DependencyListOrBuilder>(
                  dependencyList_,
                  getParentForChildren(),
                  isClean());
          dependencyList_ = null;
        }
        return dependencyListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.Project)
    }
    
    static {
      defaultInstance = new Project(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.Project)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_Project_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_Project_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproject.proto\022\014ganttproject\032\ntask.prot" +
      "o\"\244\001\n\007Project\022\014\n\004name\030\001 \001(\t\022\024\n\014organizat" +
      "ion\030\002 \001(\t\022\023\n\013project_url\030\003 \001(\t\022)\n\ttask_l" +
      "ist\030\004 \002(\0132\026.ganttproject.TaskList\0225\n\017dep" +
      "endency_list\030\005 \001(\0132\034.ganttproject.Depend" +
      "encyListB+\n\033biz.ganttproject.core.protoB" +
      "\014ProjectProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_Project_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_Project_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_Project_descriptor,
              new java.lang.String[] { "Name", "Organization", "ProjectUrl", "TaskList", "DependencyList", },
              biz.ganttproject.core.proto.ProjectProto.Project.class,
              biz.ganttproject.core.proto.ProjectProto.Project.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          biz.ganttproject.core.proto.TaskProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
