// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package biz.ganttproject.core.proto;

public final class ResourceProto {
  private ResourceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResourceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string email = 3;
    boolean hasEmail();
    String getEmail();
    
    // optional string phone = 4;
    boolean hasPhone();
    String getPhone();
    
    // optional string role_id = 5;
    boolean hasRoleId();
    String getRoleId();
  }
  public static final class Resource extends
      com.google.protobuf.GeneratedMessage
      implements ResourceOrBuilder {
    // Use Resource.newBuilder() to construct.
    private Resource(Builder builder) {
      super(builder);
    }
    private Resource(boolean noInit) {}
    
    private static final Resource defaultInstance;
    public static Resource getDefaultInstance() {
      return defaultInstance;
    }
    
    public Resource getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_Resource_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_Resource_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string phone = 4;
    public static final int PHONE_FIELD_NUMBER = 4;
    private java.lang.Object phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string role_id = 5;
    public static final int ROLE_ID_FIELD_NUMBER = 5;
    private java.lang.Object roleId_;
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getRoleId() {
      java.lang.Object ref = roleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          roleId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoleIdBytes() {
      java.lang.Object ref = roleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        roleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      phone_ = "";
      roleId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRoleIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRoleIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.ResourceProto.Resource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_Resource_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_Resource_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.ResourceProto.Resource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        roleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.ResourceProto.Resource.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.ResourceProto.Resource getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.ResourceProto.Resource.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.ResourceProto.Resource build() {
        biz.ganttproject.core.proto.ResourceProto.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.ResourceProto.Resource buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.ResourceProto.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.ResourceProto.Resource buildPartial() {
        biz.ganttproject.core.proto.ResourceProto.Resource result = new biz.ganttproject.core.proto.ResourceProto.Resource(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.roleId_ = roleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.ResourceProto.Resource) {
          return mergeFrom((biz.ganttproject.core.proto.ResourceProto.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.ResourceProto.Resource other) {
        if (other == biz.ganttproject.core.proto.ResourceProto.Resource.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              phone_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              roleId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string email = 3;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
      }
      
      // optional string phone = 4;
      private java.lang.Object phone_ = "";
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      void setPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        phone_ = value;
        onChanged();
      }
      
      // optional string role_id = 5;
      private java.lang.Object roleId_ = "";
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getRoleId() {
        java.lang.Object ref = roleId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          roleId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoleId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        roleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roleId_ = getDefaultInstance().getRoleId();
        onChanged();
        return this;
      }
      void setRoleId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        roleId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.Resource)
    }
    
    static {
      defaultInstance = new Resource(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.Resource)
  }
  
  public interface ResourceListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ganttproject.Resource resource = 1;
    java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource> 
        getResourceList();
    biz.ganttproject.core.proto.ResourceProto.Resource getResource(int index);
    int getResourceCount();
    java.util.List<? extends biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder> 
        getResourceOrBuilderList();
    biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder getResourceOrBuilder(
        int index);
  }
  public static final class ResourceList extends
      com.google.protobuf.GeneratedMessage
      implements ResourceListOrBuilder {
    // Use ResourceList.newBuilder() to construct.
    private ResourceList(Builder builder) {
      super(builder);
    }
    private ResourceList(boolean noInit) {}
    
    private static final ResourceList defaultInstance;
    public static ResourceList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResourceList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_ResourceList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_ResourceList_fieldAccessorTable;
    }
    
    // repeated .ganttproject.Resource resource = 1;
    public static final int RESOURCE_FIELD_NUMBER = 1;
    private java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource> resource_;
    public java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource> getResourceList() {
      return resource_;
    }
    public java.util.List<? extends biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder> 
        getResourceOrBuilderList() {
      return resource_;
    }
    public int getResourceCount() {
      return resource_.size();
    }
    public biz.ganttproject.core.proto.ResourceProto.Resource getResource(int index) {
      return resource_.get(index);
    }
    public biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder getResourceOrBuilder(
        int index) {
      return resource_.get(index);
    }
    
    private void initFields() {
      resource_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getResourceCount(); i++) {
        if (!getResource(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < resource_.size(); i++) {
        output.writeMessage(1, resource_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < resource_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resource_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ResourceProto.ResourceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.ResourceProto.ResourceList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.ResourceProto.ResourceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_ResourceList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.ResourceProto.internal_static_ganttproject_ResourceList_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.ResourceProto.ResourceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResourceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resourceBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.ResourceProto.ResourceList.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.ResourceProto.ResourceList getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.ResourceProto.ResourceList.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.ResourceProto.ResourceList build() {
        biz.ganttproject.core.proto.ResourceProto.ResourceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.ResourceProto.ResourceList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.ResourceProto.ResourceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.ResourceProto.ResourceList buildPartial() {
        biz.ganttproject.core.proto.ResourceProto.ResourceList result = new biz.ganttproject.core.proto.ResourceProto.ResourceList(this);
        int from_bitField0_ = bitField0_;
        if (resourceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            resource_ = java.util.Collections.unmodifiableList(resource_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.resource_ = resource_;
        } else {
          result.resource_ = resourceBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.ResourceProto.ResourceList) {
          return mergeFrom((biz.ganttproject.core.proto.ResourceProto.ResourceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.ResourceProto.ResourceList other) {
        if (other == biz.ganttproject.core.proto.ResourceProto.ResourceList.getDefaultInstance()) return this;
        if (resourceBuilder_ == null) {
          if (!other.resource_.isEmpty()) {
            if (resource_.isEmpty()) {
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResourceIsMutable();
              resource_.addAll(other.resource_);
            }
            onChanged();
          }
        } else {
          if (!other.resource_.isEmpty()) {
            if (resourceBuilder_.isEmpty()) {
              resourceBuilder_.dispose();
              resourceBuilder_ = null;
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resourceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResourceFieldBuilder() : null;
            } else {
              resourceBuilder_.addAllMessages(other.resource_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getResourceCount(); i++) {
          if (!getResource(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              biz.ganttproject.core.proto.ResourceProto.Resource.Builder subBuilder = biz.ganttproject.core.proto.ResourceProto.Resource.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResource(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ganttproject.Resource resource = 1;
      private java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource> resource_ =
        java.util.Collections.emptyList();
      private void ensureResourceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          resource_ = new java.util.ArrayList<biz.ganttproject.core.proto.ResourceProto.Resource>(resource_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.ResourceProto.Resource, biz.ganttproject.core.proto.ResourceProto.Resource.Builder, biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder> resourceBuilder_;
      
      public java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource> getResourceList() {
        if (resourceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resource_);
        } else {
          return resourceBuilder_.getMessageList();
        }
      }
      public int getResourceCount() {
        if (resourceBuilder_ == null) {
          return resource_.size();
        } else {
          return resourceBuilder_.getCount();
        }
      }
      public biz.ganttproject.core.proto.ResourceProto.Resource getResource(int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);
        } else {
          return resourceBuilder_.getMessage(index);
        }
      }
      public Builder setResource(
          int index, biz.ganttproject.core.proto.ResourceProto.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.set(index, value);
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setResource(
          int index, biz.ganttproject.core.proto.ResourceProto.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.set(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addResource(biz.ganttproject.core.proto.ResourceProto.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addResource(
          int index, biz.ganttproject.core.proto.ResourceProto.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(index, value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addResource(
          biz.ganttproject.core.proto.ResourceProto.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addResource(
          int index, biz.ganttproject.core.proto.ResourceProto.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllResource(
          java.lang.Iterable<? extends biz.ganttproject.core.proto.ResourceProto.Resource> values) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          super.addAll(values, resource_);
          onChanged();
        } else {
          resourceBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearResource() {
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resourceBuilder_.clear();
        }
        return this;
      }
      public Builder removeResource(int index) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.remove(index);
          onChanged();
        } else {
          resourceBuilder_.remove(index);
        }
        return this;
      }
      public biz.ganttproject.core.proto.ResourceProto.Resource.Builder getResourceBuilder(
          int index) {
        return getResourceFieldBuilder().getBuilder(index);
      }
      public biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder getResourceOrBuilder(
          int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);  } else {
          return resourceBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder> 
           getResourceOrBuilderList() {
        if (resourceBuilder_ != null) {
          return resourceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resource_);
        }
      }
      public biz.ganttproject.core.proto.ResourceProto.Resource.Builder addResourceBuilder() {
        return getResourceFieldBuilder().addBuilder(
            biz.ganttproject.core.proto.ResourceProto.Resource.getDefaultInstance());
      }
      public biz.ganttproject.core.proto.ResourceProto.Resource.Builder addResourceBuilder(
          int index) {
        return getResourceFieldBuilder().addBuilder(
            index, biz.ganttproject.core.proto.ResourceProto.Resource.getDefaultInstance());
      }
      public java.util.List<biz.ganttproject.core.proto.ResourceProto.Resource.Builder> 
           getResourceBuilderList() {
        return getResourceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          biz.ganttproject.core.proto.ResourceProto.Resource, biz.ganttproject.core.proto.ResourceProto.Resource.Builder, biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder> 
          getResourceFieldBuilder() {
        if (resourceBuilder_ == null) {
          resourceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              biz.ganttproject.core.proto.ResourceProto.Resource, biz.ganttproject.core.proto.ResourceProto.Resource.Builder, biz.ganttproject.core.proto.ResourceProto.ResourceOrBuilder>(
                  resource_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          resource_ = null;
        }
        return resourceBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.ResourceList)
    }
    
    static {
      defaultInstance = new ResourceList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.ResourceList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_Resource_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_Resource_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_ResourceList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_ResourceList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016resource.proto\022\014ganttproject\032\016industry" +
      ".proto\"S\n\010Resource\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002" +
      " \001(\t\022\r\n\005email\030\003 \001(\t\022\r\n\005phone\030\004 \001(\t\022\017\n\007ro" +
      "le_id\030\005 \001(\t\"8\n\014ResourceList\022(\n\010resource\030" +
      "\001 \003(\0132\026.ganttproject.ResourceB,\n\033biz.gan" +
      "ttproject.core.protoB\rResourceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_Resource_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_Resource_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "Phone", "RoleId", },
              biz.ganttproject.core.proto.ResourceProto.Resource.class,
              biz.ganttproject.core.proto.ResourceProto.Resource.Builder.class);
          internal_static_ganttproject_ResourceList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ganttproject_ResourceList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_ResourceList_descriptor,
              new java.lang.String[] { "Resource", },
              biz.ganttproject.core.proto.ResourceProto.ResourceList.class,
              biz.ganttproject.core.proto.ResourceProto.ResourceList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          biz.ganttproject.core.proto.IndustryProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
