// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package biz.ganttproject.core.proto;

public final class ViewProto {
  private ViewProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ViewOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional bool is_active = 2;
    boolean hasIsActive();
    boolean getIsActive();
    
    // optional string viewport_start_date = 3;
    boolean hasViewportStartDate();
    String getViewportStartDate();
    
    // optional int32 table_width = 4;
    boolean hasTableWidth();
    int getTableWidth();
    
    // optional string zooming = 5;
    boolean hasZooming();
    String getZooming();
    
    // repeated int32 expanded_node = 6;
    java.util.List<java.lang.Integer> getExpandedNodeList();
    int getExpandedNodeCount();
    int getExpandedNode(int index);
  }
  public static final class View extends
      com.google.protobuf.GeneratedMessage
      implements ViewOrBuilder {
    // Use View.newBuilder() to construct.
    private View(Builder builder) {
      super(builder);
    }
    private View(boolean noInit) {}
    
    private static final View defaultInstance;
    public static View getDefaultInstance() {
      return defaultInstance;
    }
    
    public View getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.ganttproject.core.proto.ViewProto.internal_static_ganttproject_View_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.ganttproject.core.proto.ViewProto.internal_static_ganttproject_View_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool is_active = 2;
    public static final int IS_ACTIVE_FIELD_NUMBER = 2;
    private boolean isActive_;
    public boolean hasIsActive() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsActive() {
      return isActive_;
    }
    
    // optional string viewport_start_date = 3;
    public static final int VIEWPORT_START_DATE_FIELD_NUMBER = 3;
    private java.lang.Object viewportStartDate_;
    public boolean hasViewportStartDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getViewportStartDate() {
      java.lang.Object ref = viewportStartDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          viewportStartDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getViewportStartDateBytes() {
      java.lang.Object ref = viewportStartDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        viewportStartDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 table_width = 4;
    public static final int TABLE_WIDTH_FIELD_NUMBER = 4;
    private int tableWidth_;
    public boolean hasTableWidth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getTableWidth() {
      return tableWidth_;
    }
    
    // optional string zooming = 5;
    public static final int ZOOMING_FIELD_NUMBER = 5;
    private java.lang.Object zooming_;
    public boolean hasZooming() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getZooming() {
      java.lang.Object ref = zooming_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          zooming_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getZoomingBytes() {
      java.lang.Object ref = zooming_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        zooming_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated int32 expanded_node = 6;
    public static final int EXPANDED_NODE_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> expandedNode_;
    public java.util.List<java.lang.Integer>
        getExpandedNodeList() {
      return expandedNode_;
    }
    public int getExpandedNodeCount() {
      return expandedNode_.size();
    }
    public int getExpandedNode(int index) {
      return expandedNode_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      isActive_ = false;
      viewportStartDate_ = "";
      tableWidth_ = 0;
      zooming_ = "";
      expandedNode_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isActive_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getViewportStartDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, tableWidth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getZoomingBytes());
      }
      for (int i = 0; i < expandedNode_.size(); i++) {
        output.writeInt32(6, expandedNode_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isActive_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getViewportStartDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tableWidth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getZoomingBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < expandedNode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(expandedNode_.get(i));
        }
        size += dataSize;
        size += 1 * getExpandedNodeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.ganttproject.core.proto.ViewProto.View parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.ganttproject.core.proto.ViewProto.View prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.ganttproject.core.proto.ViewProto.ViewOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.ganttproject.core.proto.ViewProto.internal_static_ganttproject_View_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.ganttproject.core.proto.ViewProto.internal_static_ganttproject_View_fieldAccessorTable;
      }
      
      // Construct using biz.ganttproject.core.proto.ViewProto.View.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isActive_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        viewportStartDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tableWidth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zooming_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        expandedNode_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.ganttproject.core.proto.ViewProto.View.getDescriptor();
      }
      
      public biz.ganttproject.core.proto.ViewProto.View getDefaultInstanceForType() {
        return biz.ganttproject.core.proto.ViewProto.View.getDefaultInstance();
      }
      
      public biz.ganttproject.core.proto.ViewProto.View build() {
        biz.ganttproject.core.proto.ViewProto.View result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.ganttproject.core.proto.ViewProto.View buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.ganttproject.core.proto.ViewProto.View result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.ganttproject.core.proto.ViewProto.View buildPartial() {
        biz.ganttproject.core.proto.ViewProto.View result = new biz.ganttproject.core.proto.ViewProto.View(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isActive_ = isActive_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.viewportStartDate_ = viewportStartDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tableWidth_ = tableWidth_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zooming_ = zooming_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          expandedNode_ = java.util.Collections.unmodifiableList(expandedNode_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.expandedNode_ = expandedNode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.ganttproject.core.proto.ViewProto.View) {
          return mergeFrom((biz.ganttproject.core.proto.ViewProto.View)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.ganttproject.core.proto.ViewProto.View other) {
        if (other == biz.ganttproject.core.proto.ViewProto.View.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasIsActive()) {
          setIsActive(other.getIsActive());
        }
        if (other.hasViewportStartDate()) {
          setViewportStartDate(other.getViewportStartDate());
        }
        if (other.hasTableWidth()) {
          setTableWidth(other.getTableWidth());
        }
        if (other.hasZooming()) {
          setZooming(other.getZooming());
        }
        if (!other.expandedNode_.isEmpty()) {
          if (expandedNode_.isEmpty()) {
            expandedNode_ = other.expandedNode_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureExpandedNodeIsMutable();
            expandedNode_.addAll(other.expandedNode_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isActive_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              viewportStartDate_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              tableWidth_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              zooming_ = input.readBytes();
              break;
            }
            case 48: {
              ensureExpandedNodeIsMutable();
              expandedNode_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addExpandedNode(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional bool is_active = 2;
      private boolean isActive_ ;
      public boolean hasIsActive() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsActive() {
        return isActive_;
      }
      public Builder setIsActive(boolean value) {
        bitField0_ |= 0x00000002;
        isActive_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsActive() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isActive_ = false;
        onChanged();
        return this;
      }
      
      // optional string viewport_start_date = 3;
      private java.lang.Object viewportStartDate_ = "";
      public boolean hasViewportStartDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getViewportStartDate() {
        java.lang.Object ref = viewportStartDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          viewportStartDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setViewportStartDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        viewportStartDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearViewportStartDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        viewportStartDate_ = getDefaultInstance().getViewportStartDate();
        onChanged();
        return this;
      }
      void setViewportStartDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        viewportStartDate_ = value;
        onChanged();
      }
      
      // optional int32 table_width = 4;
      private int tableWidth_ ;
      public boolean hasTableWidth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getTableWidth() {
        return tableWidth_;
      }
      public Builder setTableWidth(int value) {
        bitField0_ |= 0x00000008;
        tableWidth_ = value;
        onChanged();
        return this;
      }
      public Builder clearTableWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tableWidth_ = 0;
        onChanged();
        return this;
      }
      
      // optional string zooming = 5;
      private java.lang.Object zooming_ = "";
      public boolean hasZooming() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getZooming() {
        java.lang.Object ref = zooming_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          zooming_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setZooming(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        zooming_ = value;
        onChanged();
        return this;
      }
      public Builder clearZooming() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zooming_ = getDefaultInstance().getZooming();
        onChanged();
        return this;
      }
      void setZooming(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        zooming_ = value;
        onChanged();
      }
      
      // repeated int32 expanded_node = 6;
      private java.util.List<java.lang.Integer> expandedNode_ = java.util.Collections.emptyList();;
      private void ensureExpandedNodeIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          expandedNode_ = new java.util.ArrayList<java.lang.Integer>(expandedNode_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<java.lang.Integer>
          getExpandedNodeList() {
        return java.util.Collections.unmodifiableList(expandedNode_);
      }
      public int getExpandedNodeCount() {
        return expandedNode_.size();
      }
      public int getExpandedNode(int index) {
        return expandedNode_.get(index);
      }
      public Builder setExpandedNode(
          int index, int value) {
        ensureExpandedNodeIsMutable();
        expandedNode_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addExpandedNode(int value) {
        ensureExpandedNodeIsMutable();
        expandedNode_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllExpandedNode(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureExpandedNodeIsMutable();
        super.addAll(values, expandedNode_);
        onChanged();
        return this;
      }
      public Builder clearExpandedNode() {
        expandedNode_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ganttproject.View)
    }
    
    static {
      defaultInstance = new View(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ganttproject.View)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ganttproject_View_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ganttproject_View_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nview.proto\022\014ganttproject\"\201\001\n\004View\022\014\n\004n" +
      "ame\030\001 \001(\t\022\021\n\tis_active\030\002 \001(\010\022\033\n\023viewport" +
      "_start_date\030\003 \001(\t\022\023\n\013table_width\030\004 \001(\005\022\017" +
      "\n\007zooming\030\005 \001(\t\022\025\n\rexpanded_node\030\006 \003(\005B(" +
      "\n\033biz.ganttproject.core.protoB\tViewProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ganttproject_View_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ganttproject_View_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ganttproject_View_descriptor,
              new java.lang.String[] { "Name", "IsActive", "ViewportStartDate", "TableWidth", "Zooming", "ExpandedNode", },
              biz.ganttproject.core.proto.ViewProto.View.class,
              biz.ganttproject.core.proto.ViewProto.View.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
