name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
          java-package: jdk+fx
      - name: Build with Gradle
        run: ./gradlew build distzip

      - name: Upload to Dropbox
        env:
          ACCESS_TOKEN: ${{ secrets.GANTTPROJECT_BUILDS_ACCESS_TOKEN }}
        run: |
          cd ganttproject-builder/build/distributions
          curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer ${ACCESS_TOKEN}" \
              --header "Dropbox-API-Arg: {\"path\": \"/GanttProject Builds/ganttproject-snapshot.zip\"}" \
              --header "Content-Type: application/octet-stream" \
              --data-binary @ganttproject-3.0.0-3000.zip
