#!/bin/sh
set -e

if [ -e /usr/bin/ganttproject ]; then rm -f /usr/bin/ganttproject; fi

if [ -x "$(which update-mime >/dev/null 2>&1)" ]; then update-mime; fi

if [ -x "$(which update-menus 2>/dev/null)" ]; then update-menus; fi
